
import Navbar from "@/components/Navigation/Navbar";
import Footer from "@/components/Footer/Footer";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
<<<<<<< HEAD
        <div className="md:h-screen w-full p-0 m-0 flex flex-col text-white bg-slate-100">
=======
        <div className="md:h-screen w-full p-0 m-0 flex flex-col text-white bg-slate-100">
>>>>>>> frontend/authentication
          <header className="bg-sky-600 sticky top-0 w-full shadow">
            <Navbar/>
          </header>
          <main className="">
            {children}
          </main>
          <footer className="mt-auto bg-sky-600 w-full shadow py-4">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
