services:
  db:
    image: lehanann/pgsql:1.0-bookworm
    container_name: pgsql
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=P0sTgr3s!S3cr3TP@ssW0rd!
      - PGDATA=/var/lib/postgresql/data
      - PG_DB=ecoride
      - PG_USR=ecoride
      - PG_PWD=3c0R1dE!P@sSw0rD!AdM1
      - PG_SCHEMA=ecoride
    volumes:
      - db-ecoride:/varlib/postgresql/data

volumes:
  db-ecoride: